### ISSUE TITLE
Docker Compose with GPU support fails when using --scale option

### ISSUE THREAD

**Issue by jlaule** [beehiveai/compose#3]
## Description of the issue
When using the --scale=2 option and the docker-compose.yml file having the - device_requests:  - capabilities:  - "gpu", the docker compose fails with an error.  It appears that the capabilities array is structured differently on the subsequent containers being created and the code does not handle it properly.

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.27.0dev, build unknown
docker-py version: 4.3.1
CPython version: 3.6.8
OpenSSL version: OpenSSL 1.0.2k-fips  26 Jan 2017
```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Version:           19.03.13-beta2
 API version:       1.40
 Go version:        go1.13.14
 Git commit:        ff3fbc9d55
 Built:             Mon Aug  3 15:04:07 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13-beta2
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.14
  Git commit:       ff3fbc9d55
  Built:            Mon Aug  3 15:02:42 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
NOTE: I used asterisks to leave out sensitive information. 
```
networks:
  pytheas_network:
    driver: bridge
    ipam:
      config:
      - gateway: 192.168.253.254
        subnet: 192.168.253.0/24
      driver: default
services:
  nginx:
    container_name: nginx
    depends_on:
    - pytheas-pytorch
    - pytheas-tensorflow
    environment:
      DEPLOY_ENV: null
      http_proxy: http://********************:8080
      https_proxy: http://********************:8080
      no_proxy: e_auth
    image: ********************/docker/images/ana-dev/nginx:pytheas-gpu-
    networks:
      pytheas_network: null
    ports:
    - published: 80
      target: 80
    - published: 443
      target: 443
    restart: always
    volumes:
    - /home/ssl:/etc/ssl:rw
  pytheas-pytorch:
    device_requests:
    - capabilities:
      - gpu
    environment:
      DEPLOY_ENV: null
    expose:
    - 5000
    image: '********************/ana-dev/eos/pytheas/services/pytheas-pytorch:'
    networks:
      pytheas_network: null
    restart: always
    volumes:
    - pytheas-pytorch-snapshots:/snapshots:rw
    - pytheasdata:/pytheasdata:rw
  pytheas-tensorflow:
    device_requests:
    - capabilities:
      - gpu
    environment:
      DEPLOY_ENV: null
    expose:
    - 5000
    image: '********************/ana-dev/eos/pytheas/services/pytheas-tensorflow:'
    networks:
      pytheas_network: null
    restart: always
    volumes:
    - pytheasdata:/pytheasdata:rw
version: '3'
volumes:
  pytheas-pytorch-snapshots:
    driver: local
    driver_opts:
      device: /train_models/pytorch_snapshots
      o: bind
      type: none
  pytheasdata:
    driver: local
    driver_opts:
      device: :/data/pytheasdata
      o: nfsvers=4,addr=138.85.20.70,rw
      type: nfs

```

## Steps to reproduce the issue

1. docker-compose -p pytheas up --no-deps --force-recreate --scale pytheas-tensorflow=2 -d pytheas-tensorflow

### Observed result
Traceback (most recent call last):
File "/usr/local/bin/docker-compose", line 11, in
load_entry_point('docker-compose==1.27.0.dev0', 'console_scripts', 'docker-compose')()
File "/usr/local/lib/python3.6/site-packages/compose/cli/main.py", line 67, in main
command()
File "/usr/local/lib/python3.6/site-packages/compose/cli/main.py", line 123, in perform_command
handler(command, command_options)
File "/usr/local/lib/python3.6/site-packages/compose/cli/main.py", line 1067, in up
to_attach = up(False)
File "/usr/local/lib/python3.6/site-packages/compose/cli/main.py", line 1063, in up
cli=native_builder,
File "/usr/local/lib/python3.6/site-packages/compose/project.py", line 648, in up
get_deps,
File "/usr/local/lib/python3.6/site-packages/compose/parallel.py", line 108, in parallel_execute
raise error_to_reraise
File "/usr/local/lib/python3.6/site-packages/compose/parallel.py", line 206, in producer
result = func(obj)
File "/usr/local/lib/python3.6/site-packages/compose/project.py", line 634, in do
override_options=override_options,
File "/usr/local/lib/python3.6/site-packages/compose/service.py", line 579, in execute_convergence_plan
renew_anonymous_volumes,
File "/usr/local/lib/python3.6/site-packages/compose/service.py", line 509, in _execute_convergence_recreate
scale - len(containers), detached, start
File "/usr/local/lib/python3.6/site-packages/compose/service.py", line 479, in _execute_convergence_create
"Creating"
File "/usr/local/lib/python3.6/site-packages/compose/parallel.py", line 108, in parallel_execute
raise error_to_reraise
File "/usr/local/lib/python3.6/site-packages/compose/parallel.py", line 206, in producer
result = func(obj)
File "/usr/local/lib/python3.6/site-packages/compose/service.py", line 477, in
lambda service_name: create_and_start(self, service_name.number),
File "/usr/local/lib/python3.6/site-packages/compose/service.py", line 456, in create_and_start
container = service.create_container(number=n, quiet=True)
File "/usr/local/lib/python3.6/site-packages/compose/service.py", line 333, in create_container
previous_container=previous_container,
File "/usr/local/lib/python3.6/site-packages/compose/service.py", line 936, in _get_container_create_options
one_off=one_off)
File "/usr/local/lib/python3.6/site-packages/compose/service.py", line 1014, in _get_container_host_config
element.split(',') for element in device_request['capabilities']]
File "/usr/local/lib/python3.6/site-packages/compose/service.py", line 1014, in
element.split(',') for element in device_request['capabilities']]
AttributeError: 'list' object has no attribute 'split'

### Expected result
DEPLOY_ENV=dev docker-compose -p pytheas up --no-deps --force-recreate --scale pytheas-tensorflow=2 -d pytheas-tensorflow
Recreating pytheas_pytheas-tensorflow_1 ... 

Recreating pytheas_pytheas-tensorflow_1 ... done
Creating pytheas_pytheas-tensorflow_2   ... 

Creating pytheas_pytheas-tensorflow_2   ... done

### Stacktrace / full error message

```
Traceback (most recent call last):
File "/usr/local/bin/docker-compose", line 11, in
load_entry_point('docker-compose==1.27.0.dev0', 'console_scripts', 'docker-compose')()
File "/usr/local/lib/python3.6/site-packages/compose/cli/main.py", line 67, in main
command()
File "/usr/local/lib/python3.6/site-packages/compose/cli/main.py", line 123, in perform_command
handler(command, command_options)
File "/usr/local/lib/python3.6/site-packages/compose/cli/main.py", line 1067, in up
to_attach = up(False)
File "/usr/local/lib/python3.6/site-packages/compose/cli/main.py", line 1063, in up
cli=native_builder,
File "/usr/local/lib/python3.6/site-packages/compose/project.py", line 648, in up
get_deps,
File "/usr/local/lib/python3.6/site-packages/compose/parallel.py", line 108, in parallel_execute
raise error_to_reraise
File "/usr/local/lib/python3.6/site-packages/compose/parallel.py", line 206, in producer
result = func(obj)
File "/usr/local/lib/python3.6/site-packages/compose/project.py", line 634, in do
override_options=override_options,
File "/usr/local/lib/python3.6/site-packages/compose/service.py", line 579, in execute_convergence_plan
renew_anonymous_volumes,
File "/usr/local/lib/python3.6/site-packages/compose/service.py", line 509, in _execute_convergence_recreate
scale - len(containers), detached, start
File "/usr/local/lib/python3.6/site-packages/compose/service.py", line 479, in _execute_convergence_create
"Creating"
File "/usr/local/lib/python3.6/site-packages/compose/parallel.py", line 108, in parallel_execute
raise error_to_reraise
File "/usr/local/lib/python3.6/site-packages/compose/parallel.py", line 206, in producer
result = func(obj)
File "/usr/local/lib/python3.6/site-packages/compose/service.py", line 477, in
lambda service_name: create_and_start(self, service_name.number),
File "/usr/local/lib/python3.6/site-packages/compose/service.py", line 456, in create_and_start
container = service.create_container(number=n, quiet=True)
File "/usr/local/lib/python3.6/site-packages/compose/service.py", line 333, in create_container
previous_container=previous_container,
File "/usr/local/lib/python3.6/site-packages/compose/service.py", line 936, in _get_container_create_options
one_off=one_off)
File "/usr/local/lib/python3.6/site-packages/compose/service.py", line 1014, in _get_container_host_config
element.split(',') for element in device_request['capabilities']]
File "/usr/local/lib/python3.6/site-packages/compose/service.py", line 1014, in
element.split(',') for element in device_request['capabilities']]
AttributeError: 'list' object has no attribute 'split'
```

## Additional information

I made the following change in the compose/service.py file to get it working.  Not sure if this is a permanent solution but it at least works for me

```
        for device_request in device_requests:
            if 'capabilities' not in device_request:
                continue
            if type(device_request['capabilities'][0]) == list:
                device_request['capabilities'] = [
                    element.split('.') for element in device_request['capabilities'][0]]
            else:
                device_request['capabilities'] = [
                    element.split('.') for element in device_request['capabilities']]

```

OS version / distribution, `docker-compose` install method, etc.

**Comment by manishiitg** [comment]
i am getting the same problem as well

**Comment by jlaule** [comment]
@manishiitg Did you try making the changes I made to see if that works for you?  Not sure if you have the permissions to the file on the machine that you are executing the docker-compose on.

**Comment by manishiitg** [comment]
no. i didn't try that. 


what i do is the run the --scale command multiple time and it works
